Develop
c1n1k/airbnb-demo-frontend pull request #2
Opened 2017-11-08 17:28 UTC by c1n1k

Add Header, Explore

2017-11-09 11:53 UTC, imevro requested changes

2017-11-09 11:53 UTC, evgenyrodionov commented on src/App.js
> +import Header from "./Header/Header";
нет смысла делать такие пути, достаточно положить в `Header/index.js` — вебпак сам отрезолвит `from "./Header"`

писал об этом во втором уроке

2017-11-09 11:53 UTC, evgenyrodionov commented on src/Card/Card.js
> +        <img src="{props.img}" alt="{props.name}" />
нужно убрать кавычки, иначе не отработает подстановка пропов

2017-11-09 11:53 UTC, evgenyrodionov commented on src/Explore/Card.js
> +    </Card>
очень много префиксов `Card` при том, что мы уже находимся в Card

2017-11-09 11:53 UTC, evgenyrodionov commented on src/Explore/Card.js
> +    <Card href={props.to}>
href=to? согласованности нет

2017-11-09 11:53 UTC, evgenyrodionov commented on src/Explore/Explore.js
> +      <InnerGrid>
чем иннер отличается от иннергрид? Сходу неясно. Плохой нейминг

2017-11-09 11:53 UTC, evgenyrodionov commented on src/Header/Header.js
> +  @supports (display: grid) {
нет фоллбэков, все развалится если гридов нет

2017-11-09 11:54 UTC, evgenyrodionov commented
Кстати, зачем-то создаёшь директории ради одного файла (`Icon/Icon.js`) — бессмысленное занятие

2017-11-09 11:54 UTC, evgenyrodionov commented
И смени название пуллреквеста — он должен отражать проделанную работу

2017-11-09 14:34 UTC, c1n1k commented on src/Explore/Explore.js
> +      <InnerGrid>
по другому никак не придумал, пробовал через пропсы, пришлось отказать из-за дополнительных условий и проверок

2017-11-11 11:05 UTC, imevro requested changes

2017-11-11 11:05 UTC, evgenyrodionov commented on src/Footer/index.js
> +import optionLang from "./optionLang.js";
опусти .джс

2017-11-11 11:05 UTC, evgenyrodionov commented on src/Footer/index.js
> +  @supports (display: block) {
?

2017-11-11 11:05 UTC, evgenyrodionov commented on src/Footer/index.js
> +    grid-column: span 2;
у гридов пока плохая поддержка, давай фоллбек на флексбоксы

2017-11-11 11:05 UTC, evgenyrodionov commented on src/Footer/index.js
> +    &:nth-child(4) {
плохие селекторы

2017-11-11 11:05 UTC, evgenyrodionov commented on src/Footer/index.js
> +    &:nth-child(4) {
ненадежные

2017-11-11 11:05 UTC, evgenyrodionov commented on src/Footer/linksAirbnb.js
> +    text: "About us",
программирование конфигами хуже, чем обычный декларативный хмл

2017-11-11 11:05 UTC, evgenyrodionov commented on src/index.css
> +  overflow-x: hidden;
нет, зачем? это костыль

2017-11-11 11:05 UTC, evgenyrodionov commented on src/index.css
> +  overflow-x: hidden;
вместо исправления бага ты решил просто его скрыть

2017-11-11 11:05 UTC, evgenyrodionov commented on src/index.css
> +select::-ms-expand {
ты думаешь все селекты будут такими? а если нативный понадобится?

2017-11-11 11:39 UTC, c1n1k commented on src/index.css
> +  overflow-x: hidden;
это не исправление бага:) это на всякий случай если кнопка прокрутки на каком-то разрешении будет вызывать скролл окна страницы

2017-11-11 11:41 UTC, c1n1k commented on src/index.css
> +select::-ms-expand {
процент нативного будет существенно меньший от общего и для него уже делается вспомогалтельный класс, который будет снимать стилизацию не только с селекто но и с обёртки

2017-11-11 14:00 UTC, c1n1k commented on src/Footer/linksAirbnb.js
> +    text: "About us",
так у компонет можно переиспользовать, не дублирую разметку и стили

2017-11-12 10:25 UTC, imevro approved these changes

2017-11-12 10:26 UTC, merged

2017-11-12 10:26 UTC, evgenyrodionov commented
В мастере сделаешь гит пулл