Upd filter
c1n1k/airbnb-demo-frontend pull request #4
Opened 2017-11-28 08:45 UTC by c1n1k

Фильтры плюс немного room
https://build-heunocdxrc.now.sh

2017-11-28 21:53 UTC, evgenyrodionov commented
Куда-то плейсхолдер пропал
![image](https://user-images.githubusercontent.com/775692/33346130-b97eed5e-d49f-11e7-8a7e-be91b62a4ffe.png)

2017-11-28 21:55 UTC, evgenyrodionov commented
При энтере на апплае ничего не происходит
![image](https://user-images.githubusercontent.com/775692/33346151-cb2a0340-d49f-11e7-82f0-5d7273675714.png)

На чекбоксах таб не работает
![image](https://user-images.githubusercontent.com/775692/33346170-dd01b892-d49f-11e7-9c40-c19ce64d5e3c.png)

Да и тут тоже
![image](https://user-images.githubusercontent.com/775692/33346180-e386bb9a-d49f-11e7-8d12-6ea26f6f67de.png)

На кнопках нет курсор поинтера
![image](https://user-images.githubusercontent.com/775692/33346206-f4b96d54-d49f-11e7-8f10-81bdf241dbe3.png)

У суперхоста оч странный чекбокс + не могу проскроллить вниз + дизайн по шрифтам какой-то не такой
![image](https://user-images.githubusercontent.com/775692/33346238-0d9a71ce-d4a0-11e7-9959-084f5bf2da09.png)

2017-11-28 22:22 UTC, imevro requested changes
оч много избыточных тегов плюс можно почистить логику

2017-11-28 22:22 UTC, imevro commented on src/App.js
> +import Room from "./Room";
это всё-таки страница конкретного дома, ему больше место в Homes чем отдельно

2017-11-28 22:22 UTC, imevro commented on src/App.js
> +          <Route path="/room" component={Room} />
https://reacttraining.com/react-router/web/example/url-params

2017-11-28 22:22 UTC, imevro commented on src/Homes/Filter/Beds.js
> +        [name]: name === "bed" && value < 1 ? 1 : value
как-то костыльно выглядит

2017-11-28 22:22 UTC, imevro commented on src/Homes/Filter/Beds.js
> +      bath: this.props.rooms.bath || 0
файл же называется beds? кстатит, зачем ты используешь конструктор, если есть es class fields в кра?

2017-11-28 22:22 UTC, imevro commented on src/Homes/Filter/Beds.js
> +  SectionTitle,
оч много префиксов сектион

2017-11-28 22:22 UTC, evgenyrodionov commented on src/Homes/Filter/Dates.js
> +    /* this.setState({
мусор надо выносить

2017-11-28 22:22 UTC, evgenyrodionov commented on src/Homes/Filter/Dates.js
> +      {
а поч оно так пидорится на несколько строк? преттир что ли?

2017-11-28 22:22 UTC, evgenyrodionov commented on src/Homes/Filter/Guest.js
> +import { Guest, GuestRow, GuestLabel } from "./styled";
опять префиксы

2017-11-28 22:22 UTC, evgenyrodionov commented on src/Homes/Filter/Guest.js
> +      ...this.state,
сетстейт обновляет только переданные ключи, он не сбрасывает весь стейт

2017-11-28 22:22 UTC, evgenyrodionov commented on src/Homes/Filter/Guest.js
> +      adults: this.props.currentGuest.adults || 1,
currentGuest → values

2017-11-28 22:22 UTC, evgenyrodionov commented on src/Homes/Filter/More.js
> +  changeAmenities = (name, checked) => {
а не хочешь ключом-то передавать?  amenities / facilities

2017-11-28 22:22 UTC, evgenyrodionov commented on src/Homes/Filter/More.js
> +        <Beds rooms={this.props.rooms} onChangeHandle={this.props.onChange} />
либо onChange, либо handleChange, но не все вместе)

2017-11-28 22:22 UTC, evgenyrodionov commented on src/Homes/Filter/Price.js
> +          {...this.props}
лучше эксплиситли расписать

2017-11-30 06:07 UTC, c1n1k commented
https://build-rykgnluiou.now.sh

2017-11-30 14:43 UTC, imevro requested changes

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter.js
> +  console.log(element);
мусор

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter.js
> +      dropdown.style.height = height + "px";
ужасно! это императивщина, нельзя так делать. Ставь в стейт и назначай элементу.

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter/Dates.js
> +    console.log(nextProps);
мусор

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter/Facilities.js
> +  updateState = (name, value) => {
не оч очевидный нейминг

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter/More.js
> +  updateFilter = (name, value) => {
ну как бы ты и так в фильтре

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter/Price.js
>      this.updatePrice = this.updatePrice.bind(this);
а бинд-то зачем

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter/Price.js
>            min={this.props.minPrice}
так пропс или стейт?

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter/Rooms.js
> +          <Col>
а че за кол-то? к сетке имеет отношение? зачем путать неймингом

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Filter/rheostat.css
> +  outline: -webkit-focus-ring-color auto 5px;
а зачем вебкит?

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/Room/Book/index.js
> +  constructor(props) {
опять же конструктор

2017-11-30 14:43 UTC, evgenyrodionov commented on src/Homes/styled.js
> +  display: ${props => (props.hideOnTablet ? "none" : "inline-block")};
у нас нет терминологии desktop / tablet / mobile, есть только размер экрана, это раз

лучше используй .extend, два

2017-12-01 12:27 UTC, c1n1k commented
https://build-lrkehypbjr.now.sh

2017-12-02 14:49 UTC, evgenyrodionov commented
Что-то сломалось, почему-то не могу табом нормально переключаться

https://www.dropbox.com/s/zzht53u5btoew3e/screencast%202017-12-02%2017-45-33.mp4?dl=0

2017-12-02 14:52 UTC, imevro requested changes

2017-12-02 14:52 UTC, evgenyrodionov commented on src/Homes/Filter/Amenities.js
> +      ...this.state,
зачем?

2017-12-02 14:52 UTC, evgenyrodionov commented on src/UI/Button/index.js
> +    if (props.primary)
используй инлайновую проверку

```jsx
props => props.primary && ``
```

2017-12-02 14:52 UTC, evgenyrodionov commented on src/UI/Calendar/RangeCalendar.js
> +        {...this.props}
распиши пропы, которые туда уходят, не надо таким заниматься

2017-12-02 17:20 UTC, c1n1k commented on src/Homes/Filter/Amenities.js
> +      ...this.state,
для сброса фильтра

2017-12-02 18:08 UTC, c1n1k commented on src/UI/Calendar/RangeCalendar.js
> +        {...this.props}
это копипаст с примера, убрал

2017-12-02 18:12 UTC, c1n1k commented
https://build-gpdnjlxsdf.now.sh

2017-12-04 22:06 UTC, evgenyrodionov commented
Не коммить после запроса ревью!

2017-12-04 22:08 UTC, evgenyrodionov commented
Нашел баг — если adults не выбраны, то infants не показываются
![image](https://user-images.githubusercontent.com/775692/33578801-c80be3fa-d958-11e7-90f0-533cffcd0ab9.png)

2017-12-04 22:24 UTC, imevro requested changes

2017-12-04 22:24 UTC, evgenyrodionov commented on src/Homes/Filter/Amenities.js
> +      ...this.state,
и все же? сетстейт обновляет только переданные значения, а не весь стейт

2017-12-04 22:24 UTC, evgenyrodionov commented on src/Homes/Room/Owner.js
> +  grid-column: span 2;
supports

2017-12-05 19:17 UTC, c1n1k commented
поправил количество гостей, убрал ...this.state в Amenities, добавил фолбек для grid раскладки

2017-12-07 22:06 UTC, imevro approved these changes

2017-12-07 22:06 UTC, evgenyrodionov commented
Смерджу после мерджа #5

2017-12-08 07:48 UTC, c1n1k commented
Добавил переменную для исключения sourсemap
ПОфиксил иконку у поиска

2018-02-01 16:02 UTC, merged