Add travis
c1n1k/airbnb-demo-frontend pull request #5
Opened 2017-12-04 22:28 UTC by c1n1k

https://denisov-airbnb-demo.now.sh/

2017-12-07 22:04 UTC, evgenyrodionov commented
ПР нужно делать от того бранча, от которого бранчевался

Не забудь повесить запрос на ревью

2017-12-07 22:14 UTC, imevro requested changes

2017-12-07 22:14 UTC, evgenyrodionov commented on .travis.yml
> +  - rm build/static/js/main.*.js.map
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration

2017-12-07 22:14 UTC, evgenyrodionov commented on .travis.yml
> +deploy:
а с stage.now.sh что делаем?

2017-12-11 12:28 UTC, imevro approved these changes

2017-12-11 12:28 UTC, evgenyrodionov commented
конфликт исправь

2017-12-31 10:26 UTC, c1n1k commented
добавил heroku

2018-01-29 10:41 UTC, merged